root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main cmd/server/main.go"
  bin = "./tmp/main"
  full_bin = "APP_PORT=:8080 ./tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor"]
  log = "air.log"

[log]
  time = true

[misc]
  clean_on_exit = true